version: '3.9'

services:
  app:
    container_name: app
    build: .
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL = jdbc:postgresql://dbpg:5432/dbtienda
      - DATABASE_USERNAME = postgres
      - DATABASE_PASSWORD = postgres
    depends_on:
      - dbpg

  dbpg:

    container_name: dbpg
    image: postgres:15
    ports:
      - "5431:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dbtienda
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}